(function () {
    var supported = ['fr', 'en', 'es', 'it', 'de'];
    var appStore = 'https://apps.apple.com/fr/app/';
    var mail = 'rodolphe_vandaele@hotmail.fr';

    var ui = {
        fr: { home: 'Accueil', apps: 'Applications', support: 'Assistance', privacy: 'Confidentialité', premium: 'Premium', about: 'À propos', available: 'Disponible', soon: 'Bientôt disponible', appStore: 'Voir sur l’App Store', email: 'Contacter le support', updated: 'Mise à jour : 28 avril 2026', developer: 'Développeur indépendant', profile: 'Profil développeur', rightsTitle: 'Vos droits', rights: 'Conformément au RGPD, vous pouvez demander l’accès, la rectification, l’effacement, la limitation, la portabilité ou l’opposition au traitement de vos données personnelles. Vous pouvez aussi saisir la CNIL.', contactTitle: 'Contact', deleteTitle: 'Suppression des données', faqTitle: 'Questions fréquentes', quickSupport: 'Support rapide', dataUsed: 'Données utilisées', business: 'Publicité et achats', sources: 'Sources de données', retention: 'Conservation', download: 'Télécharger', included: 'Inclus', free: 'Gratuit', yes: 'Oui', no: 'Non' },
        en: { home: 'Home', apps: 'Apps', support: 'Support', privacy: 'Privacy', premium: 'Premium', about: 'About', available: 'Available', soon: 'Coming soon', appStore: 'View on the App Store', email: 'Contact support', updated: 'Updated: April 28, 2026', developer: 'Independent developer', profile: 'Developer profile', rightsTitle: 'Your rights', rights: 'Under the GDPR, you may request access, rectification, erasure, restriction, portability or objection regarding your personal data. You may also contact your data protection authority.', contactTitle: 'Contact', deleteTitle: 'Data deletion', faqTitle: 'FAQ', quickSupport: 'Quick support', dataUsed: 'Data used', business: 'Advertising and purchases', sources: 'Data sources', retention: 'Retention', download: 'Download', included: 'Included', free: 'Free', yes: 'Yes', no: 'No' },
        es: { home: 'Inicio', apps: 'Apps', support: 'Soporte', privacy: 'Privacidad', premium: 'Premium', about: 'Acerca de', available: 'Disponible', soon: 'Próximamente', appStore: 'Ver en el App Store', email: 'Contactar soporte', updated: 'Actualizado: 28 de abril de 2026', developer: 'Desarrollador independiente', profile: 'Perfil del desarrollador', rightsTitle: 'Tus derechos', rights: 'Según el RGPD, puedes solicitar acceso, rectificación, supresión, limitación, portabilidad u oposición respecto a tus datos personales. También puedes contactar con tu autoridad de protección de datos.', contactTitle: 'Contacto', deleteTitle: 'Eliminación de datos', faqTitle: 'Preguntas frecuentes', quickSupport: 'Soporte rápido', dataUsed: 'Datos usados', business: 'Publicidad y compras', sources: 'Fuentes de datos', retention: 'Conservación', download: 'Descargar', included: 'Incluido', free: 'Gratis', yes: 'Sí', no: 'No' },
        it: { home: 'Home', apps: 'App', support: 'Supporto', privacy: 'Privacy', premium: 'Premium', about: 'Info', available: 'Disponibile', soon: 'Presto disponibile', appStore: 'Vedi su App Store', email: 'Contatta il supporto', updated: 'Aggiornata: 28 aprile 2026', developer: 'Sviluppatore indipendente', profile: 'Profilo sviluppatore', rightsTitle: 'I tuoi diritti', rights: 'Ai sensi del GDPR puoi richiedere accesso, rettifica, cancellazione, limitazione, portabilità o opposizione al trattamento dei tuoi dati personali. Puoi anche contattare l’autorità per la protezione dei dati.', contactTitle: 'Contatto', deleteTitle: 'Eliminazione dei dati', faqTitle: 'Domande frequenti', quickSupport: 'Supporto rapido', dataUsed: 'Dati usati', business: 'Pubblicità e acquisti', sources: 'Fonti dei dati', retention: 'Conservazione', download: 'Scarica', included: 'Incluso', free: 'Gratis', yes: 'Sì', no: 'No' },
        de: { home: 'Start', apps: 'Apps', support: 'Support', privacy: 'Datenschutz', premium: 'Premium', about: 'Über', available: 'Verfügbar', soon: 'Demnächst', appStore: 'Im App Store ansehen', email: 'Support kontaktieren', updated: 'Aktualisiert: 28. April 2026', developer: 'Unabhängiger Entwickler', profile: 'Entwicklerprofil', rightsTitle: 'Deine Rechte', rights: 'Nach der DSGVO kannst du Auskunft, Berichtigung, Löschung, Einschränkung, Übertragbarkeit oder Widerspruch bezüglich deiner personenbezogenen Daten verlangen. Du kannst dich auch an deine Datenschutzbehörde wenden.', contactTitle: 'Kontakt', deleteTitle: 'Daten löschen', faqTitle: 'Häufige Fragen', quickSupport: 'Schneller Support', dataUsed: 'Verwendete Daten', business: 'Werbung und Käufe', sources: 'Datenquellen', retention: 'Aufbewahrung', download: 'Laden', included: 'Enthalten', free: 'Kostenlos', yes: 'Ja', no: 'Nein' }
    };

    var apps = {
        sosfrance: {
            name: 'SOSFrance', icon: 'sosfrance.png', type: 'sos', status: 'soon', store: '', premium: false,
            description: {
                fr: 'Numéros d’urgence, scénarios d’alerte, SMS avec position, fiche médicale et guides de premiers secours.',
                en: 'Emergency numbers, alert scenarios, location SMS, medical profile and first-aid guides.',
                es: 'Números de emergencia, escenarios de alerta, SMS con ubicación, ficha médica y guías de primeros auxilios.',
                it: 'Numeri di emergenza, scenari di allerta, SMS con posizione, profilo medico e guide di primo soccorso.',
                de: 'Notrufnummern, Alarmszenarien, SMS mit Standort, medizinisches Profil und Erste-Hilfe-Anleitungen.'
            }
        },
        carbufrance: {
            name: 'CarbuFrance', icon: 'carbufrance.png', type: 'fuel', status: 'available', store: appStore + 'carbufrance/id6760407573', premium: true, premiumPage: true,
            description: {
                fr: 'Prix des carburants en France, carte, liste, favoris, widget et outils Premium avec StoreKit.',
                en: 'French fuel prices, map, list, favorites, widget and StoreKit Premium tools.',
                es: 'Precios de carburantes en Francia, mapa, lista, favoritos, widget y herramientas Premium con StoreKit.',
                it: 'Prezzi carburanti in Francia, mappa, lista, preferiti, widget e strumenti Premium con StoreKit.',
                de: 'Kraftstoffpreise in Frankreich, Karte, Liste, Favoriten, Widget und Premium-Tools mit StoreKit.'
            }
        },
        irvefrance: {
            name: 'IRVEFrance', icon: 'irvefrance.png', type: 'ev', status: 'available', store: appStore + 'irvefrance/id6760716931', premium: true, premiumPage: true,
            description: {
                fr: 'Bornes de recharge électriques, réseaux, connecteurs, puissance, disponibilité et guidage.',
                en: 'EV charging stations, networks, connectors, power, availability and directions.',
                es: 'Puntos de recarga eléctrica, redes, conectores, potencia, disponibilidad y rutas.',
                it: 'Colonnine di ricarica, reti, connettori, potenza, disponibilità e navigazione.',
                de: 'Ladestationen, Netze, Anschlüsse, Leistung, Verfügbarkeit und Navigation.'
            }
        },
        toilettefrance: {
            name: 'ToiletteFrance', icon: 'toilettefrance.png', type: 'toilet', status: 'available', store: appStore + 'toilettefrance/id6760978805', premium: false,
            description: {
                fr: 'Toilettes publiques en France, carte, filtres utiles, accessibilité, horaires et guidage.',
                en: 'Public toilets in France, map, useful filters, accessibility, opening hours and directions.',
                es: 'Baños públicos en Francia, mapa, filtros útiles, accesibilidad, horarios y rutas.',
                it: 'Bagni pubblici in Francia, mappa, filtri utili, accessibilità, orari e navigazione.',
                de: 'Öffentliche Toiletten in Frankreich, Karte, Filter, Barrierefreiheit, Öffnungszeiten und Navigation.'
            }
        },
        defibfrance: {
            name: 'DefibFrance', icon: 'defibfrance.png', type: 'defib', status: 'available', store: appStore + 'defibfrance/id6761717722', premium: false,
            description: {
                fr: 'Défibrillateurs automatisés externes, disponibilité, accessibilité et guidage d’urgence.',
                en: 'Automated external defibrillators, availability, accessibility and emergency directions.',
                es: 'Desfibriladores externos automáticos, disponibilidad, accesibilidad y rutas de emergencia.',
                it: 'Defibrillatori automatici esterni, disponibilità, accessibilità e navigazione di emergenza.',
                de: 'Automatisierte externe Defibrillatoren, Verfügbarkeit, Zugänglichkeit und Notfallnavigation.'
            }
        }
    };

    var commonCopy = {
        fr: { homeLead: 'Applications iOS pensées pour le quotidien, les urgences, la mobilité et les services publics en France.', deletion: 'L’application ne crée pas de compte utilisateur. Les données locales se suppriment en désinstallant l’application ou depuis les réglages quand l’option existe.', adDetails: 'Google AdMob peut traiter des identifiants publicitaires, l’adresse IP, le modèle d’appareil, des données de performance et les interactions publicitaires. Consultez la politique de confidentialité de Google.', retention: 'Les données locales restent sur votre appareil jusqu’à suppression de l’app ou réinitialisation des réglages. Les données publicitaires suivent les règles de Google AdMob et les achats suivent les règles Apple quand ils existent.', feature: 'Fonction', featuresTitle: 'Fonctionnalités' },
        en: { homeLead: 'iOS apps designed for everyday needs, emergencies, mobility and public services in France.', deletion: 'The app does not create a user account. Local data can be removed by deleting the app or from settings when an option exists.', adDetails: 'Google AdMob may process advertising identifiers, IP address, device model, performance data and ad interactions. See Google’s privacy policy.', retention: 'Local data remains on your device until you delete the app or reset settings. Advertising data follows Google AdMob rules and purchases follow Apple rules when they exist.', feature: 'Feature', featuresTitle: 'Features' },
        es: { homeLead: 'Apps iOS pensadas para el día a día, emergencias, movilidad y servicios públicos en Francia.', deletion: 'La app no crea una cuenta de usuario. Los datos locales se eliminan al desinstalar la app o desde los ajustes cuando existe la opción.', adDetails: 'Google AdMob puede tratar identificadores publicitarios, dirección IP, modelo del dispositivo, datos de rendimiento e interacciones con anuncios. Consulta la política de privacidad de Google.', retention: 'Los datos locales permanecen en tu dispositivo hasta que eliminas la app o restableces los ajustes. Los datos publicitarios siguen las reglas de Google AdMob y las compras siguen las reglas de Apple cuando existen.', feature: 'Función', featuresTitle: 'Funciones' },
        it: { homeLead: 'App iOS pensate per quotidiano, emergenze, mobilità e servizi pubblici in Francia.', deletion: 'L’app non crea un account utente. I dati locali si eliminano disinstallando l’app o dalle impostazioni quando l’opzione esiste.', adDetails: 'Google AdMob può trattare identificatori pubblicitari, indirizzo IP, modello del dispositivo, dati di prestazione e interazioni con gli annunci. Consulta la privacy policy di Google.', retention: 'I dati locali restano sul dispositivo finché elimini l’app o ripristini le impostazioni. I dati pubblicitari seguono le regole Google AdMob e gli acquisti seguono le regole Apple quando esistono.', feature: 'Funzione', featuresTitle: 'Funzionalità' },
        de: { homeLead: 'iOS-Apps für Alltag, Notfälle, Mobilität und öffentliche Dienste in Frankreich.', deletion: 'Die App erstellt kein Benutzerkonto. Lokale Daten können durch Löschen der App oder in den Einstellungen entfernt werden, wenn eine Option vorhanden ist.', adDetails: 'Google AdMob kann Werbe-IDs, IP-Adresse, Gerätemodell, Leistungsdaten und Anzeigeninteraktionen verarbeiten. Siehe die Datenschutzerklärung von Google.', retention: 'Lokale Daten bleiben auf deinem Gerät, bis du die App löschst oder Einstellungen zurücksetzt. Werbedaten folgen den Regeln von Google AdMob und Käufe den Regeln von Apple, wenn sie existieren.', feature: 'Funktion', featuresTitle: 'Funktionen' }
    };

    var appFeatures = {
        carbufrance: {
            fr: ['Carte et liste des stations avec prix carburants en France.', 'Tri par prix ou distance, favoris, stations masquées et cache hors-ligne.', 'Widget station la moins chère avec actions Premium.', 'Carnet de bord, entretien et observatoire des marchés en Premium.'],
            en: ['Map and list of French fuel stations with prices.', 'Sort by price or distance, favorites, hidden stations and offline cache.', 'Cheapest-station widget with Premium actions.', 'Logbook, maintenance and market observatory in Premium.'],
            es: ['Mapa y lista de estaciones francesas con precios.', 'Orden por precio o distancia, favoritos, ocultar estaciones y caché offline.', 'Widget de estación más barata con acciones Premium.', 'Registro, mantenimiento y observatorio de mercados en Premium.'],
            it: ['Mappa e lista delle stazioni francesi con prezzi.', 'Ordina per prezzo o distanza, preferiti, stazioni nascoste e cache offline.', 'Widget stazione più economica con azioni Premium.', 'Registro, manutenzione e osservatorio mercati in Premium.'],
            de: ['Karte und Liste französischer Tankstellen mit Preisen.', 'Sortierung nach Preis oder Entfernung, Favoriten, ausgeblendete Stationen und Offline-Cache.', 'Widget für die günstigste Tankstelle mit Premium-Aktionen.', 'Fahrtenbuch, Wartung und Marktüberblick in Premium.']
        },
        irvefrance: {
            fr: ['Carte des bornes avec connecteurs, puissance, opérateur et disponibilité.', 'Filtres CCS2, CHAdeMO, Type 2, puissance minimale et rayon 5 à 50 km.', 'Look Around, vue 3D, favoris, hors-ligne, Siri et calculateur de recharge.', 'Premium : tarifs réseaux, coût de recharge, conseils et actualités mobilité électrique.'],
            en: ['Charger map with connectors, power, operator and availability.', 'CCS2, CHAdeMO, Type 2, minimum power and 5 to 50 km radius filters.', 'Look Around, 3D map, favorites, offline mode, Siri and charging calculator.', 'Premium: network rates, charging cost, advice and EV news.'],
            es: ['Mapa de cargadores con conectores, potencia, operador y disponibilidad.', 'Filtros CCS2, CHAdeMO, Type 2, potencia mínima y radio de 5 a 50 km.', 'Look Around, mapa 3D, favoritos, offline, Siri y calculadora de recarga.', 'Premium: tarifas de redes, coste de recarga, consejos y noticias de movilidad eléctrica.'],
            it: ['Mappa colonnine con connettori, potenza, operatore e disponibilità.', 'Filtri CCS2, CHAdeMO, Type 2, potenza minima e raggio da 5 a 50 km.', 'Look Around, mappa 3D, preferiti, offline, Siri e calcolatore ricarica.', 'Premium: tariffe reti, costo ricarica, consigli e notizie mobilità elettrica.'],
            de: ['Ladekarte mit Anschlüssen, Leistung, Betreiber und Verfügbarkeit.', 'Filter für CCS2, CHAdeMO, Type 2, Mindestleistung und 5 bis 50 km Radius.', 'Look Around, 3D-Karte, Favoriten, Offline-Modus, Siri und Laderechner.', 'Premium: Netzwerktarife, Ladekosten, Hinweise und E-Mobility-News.']
        },
        defibfrance: {
            fr: ['Carte des DAE proches avec code couleur par accessibilité.', 'Filtres accès public, 24h/24, intérieur/extérieur et rayon 500 m à 10 km.', 'Mode Urgence, appel SAMU 15 avec confirmation et guide RCP avec métronome haptique.', 'Application gratuite, sans abonnement, avec vidéo récompensée pour retirer la publicité temporairement.'],
            en: ['Nearby AED map with color coding by accessibility.', 'Public access, 24/7, indoor/outdoor and 500 m to 10 km radius filters.', 'Emergency mode, SAMU 15 call confirmation and CPR guide with haptic metronome.', 'Free app, no subscription, with rewarded video to temporarily remove ads.'],
            es: ['Mapa de DAE cercanos con colores por accesibilidad.', 'Filtros acceso público, 24/7, interior/exterior y radio de 500 m a 10 km.', 'Modo Emergencia, confirmación de llamada SAMU 15 y guía RCP con metrónomo háptico.', 'App gratuita, sin suscripción, con vídeo recompensado para quitar anuncios temporalmente.'],
            it: ['Mappa DAE vicini con colori per accessibilità.', 'Filtri accesso pubblico, 24/7, interno/esterno e raggio da 500 m a 10 km.', 'Modalità Emergenza, conferma chiamata SAMU 15 e guida RCP con metronomo aptico.', 'App gratuita, senza abbonamento, con video premiato per rimuovere temporaneamente gli annunci.'],
            de: ['Karte naher AEDs mit Farbcodierung nach Zugänglichkeit.', 'Filter für öffentlichen Zugang, 24/7, innen/außen und 500 m bis 10 km Radius.', 'Notfallmodus, SAMU-15-Anrufbestätigung und CPR-Anleitung mit haptischem Metronom.', 'Kostenlose App ohne Abo, mit belohntem Video zum zeitweisen Entfernen von Werbung.']
        },
        toilettefrance: {
            fr: ['Carte des toilettes publiques en France avec distance et guidage.', 'Filtres d’accessibilité, horaires et informations disponibles selon les données ouvertes.', 'Favoris, préférences et données locales sans compte utilisateur.', 'Application gratuite financée par publicité AdMob.'],
            en: ['Map of public toilets in France with distance and directions.', 'Accessibility filters, opening hours and available details from open data.', 'Favorites, preferences and local data with no user account.', 'Free app funded by AdMob ads.'],
            es: ['Mapa de baños públicos en Francia con distancia y rutas.', 'Filtros de accesibilidad, horarios e información disponible desde datos abiertos.', 'Favoritos, preferencias y datos locales sin cuenta de usuario.', 'App gratuita financiada con anuncios AdMob.'],
            it: ['Mappa dei bagni pubblici in Francia con distanza e navigazione.', 'Filtri accessibilità, orari e dettagli disponibili da dati aperti.', 'Preferiti, preferenze e dati locali senza account utente.', 'App gratuita finanziata da annunci AdMob.'],
            de: ['Karte öffentlicher Toiletten in Frankreich mit Entfernung und Route.', 'Barrierefreiheitsfilter, Öffnungszeiten und verfügbare Details aus offenen Daten.', 'Favoriten, Einstellungen und lokale Daten ohne Benutzerkonto.', 'Kostenlose App, finanziert durch AdMob-Werbung.']
        },
        sosfrance: {
            fr: ['Numéros d’urgence français, scénarios d’alerte et guides de premiers secours.', 'SMS préparé avec position GPS et confirmation manuelle imposée par iOS.', 'Fiche médicale, contacts d’urgence et données Apple Santé uniquement avec consentement.', 'Catégorie bientôt disponible dans le site tant que la publication n’est pas active.'],
            en: ['French emergency numbers, alert scenarios and first-aid guides.', 'Prepared SMS with GPS location and manual confirmation required by iOS.', 'Medical profile, emergency contacts and Apple Health data only with consent.', 'Shown in the coming-soon category until publication is active.'],
            es: ['Números de emergencia franceses, escenarios de alerta y guías de primeros auxilios.', 'SMS preparado con ubicación GPS y confirmación manual exigida por iOS.', 'Ficha médica, contactos de emergencia y datos Apple Salud solo con consentimiento.', 'Se muestra en la categoría próximamente hasta que la publicación esté activa.'],
            it: ['Numeri di emergenza francesi, scenari di allerta e guide di primo soccorso.', 'SMS preparato con posizione GPS e conferma manuale richiesta da iOS.', 'Profilo medico, contatti di emergenza e dati Apple Salute solo con consenso.', 'Mostrata nella categoria prossimamente finché la pubblicazione non è attiva.'],
            de: ['Französische Notrufnummern, Alarmszenarien und Erste-Hilfe-Anleitungen.', 'Vorbereitete SMS mit GPS-Standort und manueller iOS-Bestätigung.', 'Medizinisches Profil, Notfallkontakte und Apple-Health-Daten nur mit Zustimmung.', 'In der Demnächst-Kategorie, bis die Veröffentlichung aktiv ist.']
        }
    };

    var typeText = {
        fuel: {
            fr: { data: 'La position sert à afficher les stations proches, calculer les distances et ouvrir un itinéraire. Les favoris, stations masquées, préférences, langue, cache hors-ligne, carnet de bord et entretien restent sur l’appareil.', source: 'Les prix viennent du jeu de données public du Ministère de l’Économie. Les informations de marché peuvent provenir de flux publics financiers ou d’actualité.', support: [['Les prix ne sont pas à jour ?', 'Les prix dépendent des déclarations des stations. Si aucune mise à jour récente n’existe, l’app conserve la dernière valeur disponible.'], ['Le widget affiche mal les actions ?', 'Le widget gratuit montre la station la moins chère. Les actions rapides sont Premium et utilisent des icônes compactes pour rester lisibles.'], ['Comment restaurer Premium ?', 'Ouvrez CarbuFrance puis Réglages › Premium. StoreKit et votre compte Apple gèrent la restauration.']] },
            en: { data: 'Location is used to show nearby stations, calculate distances and open directions. Favorites, hidden stations, preferences, language, offline cache, logbook and maintenance stay on device.', source: 'Prices come from the public dataset of the French Ministry of Economy. Market information may come from public financial or news feeds.', support: [['Prices are not up to date?', 'Prices depend on station reports. If no recent update exists, the app keeps the latest available value.'], ['Widget actions look wrong?', 'The free widget shows the cheapest station. Quick actions are Premium and use compact icons to remain readable.'], ['How do I restore Premium?', 'Open CarbuFrance then Settings › Premium. StoreKit and your Apple account handle restoration.']] },
            es: { data: 'La ubicación sirve para mostrar estaciones cercanas, calcular distancias y abrir rutas. Favoritos, estaciones ocultas, preferencias, idioma, caché, registro y mantenimiento permanecen en el dispositivo.', source: 'Los precios vienen del conjunto público del Ministerio de Economía francés. La información de mercado puede venir de fuentes públicas financieras o de noticias.', support: [['¿Los precios no están actualizados?', 'Los precios dependen de las declaraciones de las estaciones. Si no hay una actualización reciente, la app conserva el último valor disponible.'], ['¿Las acciones del widget se ven mal?', 'El widget gratuito muestra la estación más barata. Las acciones rápidas son Premium y usan iconos compactos para ser legibles.'], ['¿Cómo restauro Premium?', 'Abre CarbuFrance y Ajustes › Premium. StoreKit y tu cuenta Apple gestionan la restauración.']] },
            it: { data: 'La posizione serve per mostrare le stazioni vicine, calcolare le distanze e aprire itinerari. Preferiti, stazioni nascoste, preferenze, lingua, cache, registro e manutenzione restano sul dispositivo.', source: 'I prezzi provengono dal dataset pubblico del Ministero dell’Economia francese. Le informazioni di mercato possono arrivare da fonti finanziarie o notizie pubbliche.', support: [['I prezzi non sono aggiornati?', 'I prezzi dipendono dalle dichiarazioni delle stazioni. Se non esiste un aggiornamento recente, l’app mantiene l’ultimo valore disponibile.'], ['Le azioni del widget sono visualizzate male?', 'Il widget gratuito mostra la stazione più economica. Le azioni rapide sono Premium e usano icone compatte per restare leggibili.'], ['Come ripristino Premium?', 'Apri CarbuFrance e Impostazioni › Premium. StoreKit e il tuo account Apple gestiscono il ripristino.']] },
            de: { data: 'Der Standort zeigt nahe Tankstellen, berechnet Entfernungen und öffnet Routen. Favoriten, ausgeblendete Tankstellen, Einstellungen, Sprache, Offline-Cache, Fahrtenbuch und Wartung bleiben auf dem Gerät.', source: 'Die Preise stammen aus dem öffentlichen Datensatz des französischen Wirtschaftsministeriums. Marktinformationen können aus öffentlichen Finanz- oder Nachrichtenquellen stammen.', support: [['Sind Preise nicht aktuell?', 'Preise hängen von Meldungen der Tankstellen ab. Ohne neue Meldung behält die App den letzten verfügbaren Wert.'], ['Sehen Widget-Aktionen falsch aus?', 'Das kostenlose Widget zeigt die günstigste Tankstelle. Schnellaktionen sind Premium und nutzen kompakte Symbole.'], ['Wie stelle ich Premium wieder her?', 'Öffne CarbuFrance und Einstellungen › Premium. StoreKit und dein Apple-Konto übernehmen die Wiederherstellung.']] }
        },
        ev: {
            fr: { data: 'La position sert à afficher les bornes proches, les connecteurs, la puissance, les réseaux et le guidage. Favoris, filtres et préférences restent localement.', source: 'Les bornes proviennent d’OpenChargeMap, OpenStreetMap et de données publiques agrégées selon les disponibilités.', support: [['Une borne manque ?', 'Les données dépendent des opérateurs et bases ouvertes. Une borne peut apparaître avec retard.'], ['La disponibilité semble fausse ?', 'Les informations temps réel varient selon les réseaux. Vérifiez toujours sur place avant un trajet critique.'], ['Comment restaurer Premium ?', 'Ouvrez IRVEFrance › Réglages › Premium. StoreKit et votre compte Apple gèrent la restauration.']] },
            en: { data: 'Location shows nearby chargers, connectors, power, networks and directions. Favorites, filters and preferences stay local.', source: 'Chargers come from OpenChargeMap, OpenStreetMap and aggregated public datasets depending on availability.', support: [['A charger is missing?', 'Data depends on operators and open databases. Some chargers may appear later.'], ['Availability looks wrong?', 'Live availability varies by network. Always check on site before a critical trip.'], ['How do I restore Premium?', 'Open IRVEFrance › Settings › Premium. StoreKit and your Apple account handle restoration.']] },
            es: { data: 'La ubicación muestra cargadores cercanos, conectores, potencia, redes y rutas. Favoritos, filtros y preferencias permanecen localmente.', source: 'Los cargadores proceden de OpenChargeMap, OpenStreetMap y datos públicos agregados según disponibilidad.', support: [['¿Falta un cargador?', 'Los datos dependen de operadores y bases abiertas. Algunos cargadores pueden aparecer más tarde.'], ['¿La disponibilidad parece errónea?', 'La disponibilidad en vivo varía por red. Comprueba siempre antes de un viaje crítico.'], ['¿Cómo restauro Premium?', 'Abre IRVEFrance › Ajustes › Premium. StoreKit y tu cuenta Apple gestionan la restauración.']] },
            it: { data: 'La posizione mostra colonnine vicine, connettori, potenza, reti e navigazione. Preferiti, filtri e preferenze restano locali.', source: 'Le colonnine provengono da OpenChargeMap, OpenStreetMap e dataset pubblici aggregati secondo disponibilità.', support: [['Manca una colonnina?', 'I dati dipendono da operatori e basi aperte. Alcune colonnine possono apparire in ritardo.'], ['La disponibilità sembra errata?', 'La disponibilità live varia per rete. Verifica sempre prima di un viaggio critico.'], ['Come ripristino Premium?', 'Apri IRVEFrance › Impostazioni › Premium. StoreKit e il tuo account Apple gestiscono il ripristino.']] },
            de: { data: 'Der Standort zeigt nahe Ladepunkte, Anschlüsse, Leistung, Netze und Routen. Favoriten, Filter und Einstellungen bleiben lokal.', source: 'Ladepunkte stammen aus OpenChargeMap, OpenStreetMap und aggregierten öffentlichen Datensätzen.', support: [['Fehlt ein Ladepunkt?', 'Daten hängen von Betreibern und offenen Datenbanken ab. Manche Ladepunkte erscheinen später.'], ['Wirkt Verfügbarkeit falsch?', 'Live-Verfügbarkeit variiert je Netz. Prüfe vor kritischen Fahrten zusätzlich vor Ort.'], ['Wie stelle ich Premium wieder her?', 'Öffne IRVEFrance › Einstellungen › Premium. StoreKit und dein Apple-Konto übernehmen die Wiederherstellung.']] }
        },
        defib: {
            fr: { data: 'La position sert à afficher les défibrillateurs proches, leur accessibilité et le guidage d’urgence. Favoris et préférences restent localement.', source: 'Les données proviennent de bases ouvertes comme data.gouv.fr et OpenStreetMap selon les zones.', support: [['Un défibrillateur manque ?', 'Les bases ouvertes peuvent être incomplètes. En urgence, appelez toujours les secours.'], ['Que signifient les couleurs ?', 'Elles indiquent l’accès public, restreint ou incertain selon les informations disponibles.'], ['La localisation ne fonctionne pas ?', 'Vérifiez l’autorisation de localisation dans les réglages iOS de DefibFrance.']] },
            en: { data: 'Location shows nearby defibrillators, accessibility and emergency directions. Favorites and preferences stay local.', source: 'Data comes from open databases such as data.gouv.fr and OpenStreetMap depending on the area.', support: [['A defibrillator is missing?', 'Open databases may be incomplete. In an emergency, always call emergency services.'], ['What do colors mean?', 'They indicate public, limited or uncertain access based on available information.'], ['Location is not working?', 'Check location permission in iOS settings for DefibFrance.']] },
            es: { data: 'La ubicación muestra desfibriladores cercanos, accesibilidad y rutas de emergencia. Favoritos y preferencias permanecen localmente.', source: 'Los datos proceden de bases abiertas como data.gouv.fr y OpenStreetMap según la zona.', support: [['¿Falta un desfibrilador?', 'Las bases abiertas pueden estar incompletas. En emergencia, llama siempre a los servicios de emergencia.'], ['¿Qué significan los colores?', 'Indican acceso público, limitado o incierto según la información disponible.'], ['¿La ubicación no funciona?', 'Comprueba el permiso de ubicación en los ajustes iOS de DefibFrance.']] },
            it: { data: 'La posizione mostra defibrillatori vicini, accessibilità e navigazione di emergenza. Preferiti e preferenze restano locali.', source: 'I dati provengono da basi aperte come data.gouv.fr e OpenStreetMap secondo le zone.', support: [['Manca un defibrillatore?', 'Le basi aperte possono essere incomplete. In emergenza chiama sempre i soccorsi.'], ['Cosa indicano i colori?', 'Indicano accesso pubblico, limitato o incerto secondo le informazioni disponibili.'], ['La posizione non funziona?', 'Controlla il permesso di localizzazione nelle impostazioni iOS di DefibFrance.']] },
            de: { data: 'Der Standort zeigt nahe Defibrillatoren, Zugänglichkeit und Notfallnavigation. Favoriten und Einstellungen bleiben lokal.', source: 'Daten stammen je nach Gebiet aus offenen Quellen wie data.gouv.fr und OpenStreetMap.', support: [['Fehlt ein Defibrillator?', 'Offene Datenbanken können unvollständig sein. Im Notfall immer den Rettungsdienst rufen.'], ['Was bedeuten die Farben?', 'Sie zeigen öffentlichen, eingeschränkten oder unklaren Zugang nach verfügbaren Informationen.'], ['Funktioniert der Standort nicht?', 'Prüfe die Standortberechtigung in den iOS-Einstellungen von DefibFrance.']] }
        },
        toilet: {
            fr: { data: 'La position sert à afficher les toilettes publiques proches, calculer les distances, filtrer l’accessibilité et ouvrir un itinéraire. Favoris et préférences restent localement.', source: 'Les données proviennent de data.gouv.fr, OpenStreetMap et de bases ouvertes locales selon les communes.', support: [['Des toilettes manquent ?', 'Les bases ouvertes ne sont pas toujours complètes. Les communes publient les données à des rythmes différents.'], ['L’accessibilité est inconnue ?', 'Certaines données ne renseignent pas encore l’accessibilité. L’app affiche l’information quand elle existe.'], ['La localisation ne fonctionne pas ?', 'Vérifiez l’autorisation de localisation dans les réglages iOS de ToiletteFrance.']] },
            en: { data: 'Location shows nearby public toilets, calculates distances, filters accessibility and opens directions. Favorites and preferences stay local.', source: 'Data comes from data.gouv.fr, OpenStreetMap and local open datasets depending on municipalities.', support: [['A toilet is missing?', 'Open datasets are not always complete. Municipalities publish data at different rhythms.'], ['Accessibility is unknown?', 'Some datasets do not include accessibility yet. The app shows it when available.'], ['Location is not working?', 'Check location permission in iOS settings for ToiletteFrance.']] },
            es: { data: 'La ubicación muestra baños públicos cercanos, calcula distancias, filtra accesibilidad y abre rutas. Favoritos y preferencias permanecen localmente.', source: 'Los datos proceden de data.gouv.fr, OpenStreetMap y datos abiertos locales según los municipios.', support: [['¿Falta un baño?', 'Las bases abiertas no siempre están completas. Los municipios publican datos a ritmos distintos.'], ['¿La accesibilidad es desconocida?', 'Algunas bases aún no incluyen accesibilidad. La app la muestra cuando existe.'], ['¿La ubicación no funciona?', 'Comprueba el permiso de ubicación en los ajustes iOS de ToiletteFrance.']] },
            it: { data: 'La posizione mostra bagni pubblici vicini, calcola distanze, filtra accessibilità e apre itinerari. Preferiti e preferenze restano locali.', source: 'I dati provengono da data.gouv.fr, OpenStreetMap e dataset locali aperti secondo i comuni.', support: [['Manca un bagno?', 'Le basi aperte non sono sempre complete. I comuni pubblicano i dati con ritmi diversi.'], ['Accessibilità sconosciuta?', 'Alcuni dataset non includono ancora l’accessibilità. L’app la mostra quando disponibile.'], ['La posizione non funziona?', 'Controlla il permesso di localizzazione nelle impostazioni iOS di ToiletteFrance.']] },
            de: { data: 'Der Standort zeigt nahe öffentliche Toiletten, berechnet Entfernungen, filtert Barrierefreiheit und öffnet Routen. Favoriten und Einstellungen bleiben lokal.', source: 'Daten stammen aus data.gouv.fr, OpenStreetMap und lokalen offenen Datensätzen je nach Gemeinde.', support: [['Fehlt eine Toilette?', 'Offene Datensätze sind nicht immer vollständig. Gemeinden veröffentlichen Daten unterschiedlich schnell.'], ['Barrierefreiheit unbekannt?', 'Manche Daten enthalten noch keine Barrierefreiheit. Die App zeigt sie, wenn verfügbar.'], ['Funktioniert der Standort nicht?', 'Prüfe die Standortberechtigung in den iOS-Einstellungen von ToiletteFrance.']] }
        },
        sos: {
            fr: { data: 'La position enrichit uniquement les SMS d’urgence que vous préparez. Contacts d’urgence, fiche médicale, scénarios et préférences restent sur l’appareil. Les données Apple Santé sont lues seulement avec votre accord.', source: 'Les numéros, scénarios et guides sont intégrés dans l’application et pensés pour les urgences en France.', support: [['Le SMS ne part pas ?', 'iOS impose une confirmation manuelle. Relisez le message puis touchez Envoyer dans Messages.'], ['La position manque dans le SMS ?', 'Vérifiez l’autorisation de localisation dans les réglages iOS de SOSFrance.'], ['Les données Santé ne s’affichent pas ?', 'Autorisez Apple Santé depuis l’app ou les réglages iOS, puis relancez la fiche médicale.']] },
            en: { data: 'Location only enriches emergency SMS messages you prepare. Emergency contacts, medical profile, scenarios and preferences stay on device. Apple Health data is read only with your consent.', source: 'Numbers, scenarios and guides are bundled in the app and designed for emergencies in France.', support: [['SMS does not send?', 'iOS requires manual confirmation. Review the message then tap Send in Messages.'], ['Location is missing in SMS?', 'Check location permission in iOS settings for SOSFrance.'], ['Health data does not show?', 'Allow Apple Health from the app or iOS settings, then reopen the medical profile.']] },
            es: { data: 'La ubicación solo enriquece los SMS de emergencia que preparas. Contactos, ficha médica, escenarios y preferencias permanecen en el dispositivo. Los datos de Apple Salud se leen solo con tu permiso.', source: 'Números, escenarios y guías están integrados en la app y pensados para emergencias en Francia.', support: [['¿El SMS no se envía?', 'iOS exige confirmación manual. Revisa el mensaje y toca Enviar en Mensajes.'], ['¿Falta la ubicación en el SMS?', 'Comprueba el permiso de ubicación en los ajustes iOS de SOSFrance.'], ['¿No aparecen los datos de Salud?', 'Autoriza Apple Salud desde la app o ajustes iOS y vuelve a abrir la ficha médica.']] },
            it: { data: 'La posizione arricchisce solo gli SMS di emergenza che prepari. Contatti, profilo medico, scenari e preferenze restano sul dispositivo. I dati Apple Salute vengono letti solo con consenso.', source: 'Numeri, scenari e guide sono integrati nell’app e pensati per le emergenze in Francia.', support: [['L’SMS non parte?', 'iOS richiede conferma manuale. Controlla il messaggio e tocca Invia in Messaggi.'], ['Manca la posizione nell’SMS?', 'Controlla il permesso di localizzazione nelle impostazioni iOS di SOSFrance.'], ['I dati Salute non appaiono?', 'Autorizza Apple Salute dall’app o dalle impostazioni iOS e riapri il profilo medico.']] },
            de: { data: 'Der Standort ergänzt nur Notfall-SMS, die du vorbereitest. Notfallkontakte, medizinisches Profil, Szenarien und Einstellungen bleiben auf dem Gerät. Apple-Health-Daten werden nur mit Zustimmung gelesen.', source: 'Nummern, Szenarien und Anleitungen sind in der App enthalten und für Notfälle in Frankreich gedacht.', support: [['SMS wird nicht gesendet?', 'iOS verlangt manuelle Bestätigung. Prüfe die Nachricht und tippe in Nachrichten auf Senden.'], ['Standort fehlt in der SMS?', 'Prüfe die Standortberechtigung in den iOS-Einstellungen von SOSFrance.'], ['Gesundheitsdaten erscheinen nicht?', 'Erlaube Apple Health in der App oder in iOS und öffne das medizinische Profil erneut.']] }
        }
    };

    var premium = {
        carbufrance: {
        fr: { title: 'Pass Premium', subtitle: 'Prix, marché, carnet et widget sans publicité.', eyebrow: 'CarbuFrance Premium', heading: 'Tout ce qui aide vraiment à décider où faire le plein.', lead: 'La version gratuite garde l’essentiel. Premium retire la publicité et ajoute les outils d’analyse, de suivi véhicule et d’action rapide.', note: '7 jours d’essai gratuit, puis prix affiché dans l’app', features: [['Sans publicité', 'Plus de bannière, interstitiel ou vidéo récompensée.'], ['Observatoire des marchés', 'Brent, EUR/USD, tendances et actualités.'], ['Carnet de bord', 'Pleins, litres, dépenses, L/100 km et budget.'], ['Entretien véhicule', 'Interventions, rappels et coût total.'], ['Actions widget', 'Navigation, ajout d’un plein et actualisation.']], rows: [['Prix, carte, liste, favoris', true, true], ['Widget station la moins chère', true, true], ['Publicités supprimées', false, true], ['Marchés et moyennes', false, true], ['Carnet, entretien, actions widget', false, true]], activate: 'Ouvrez CarbuFrance › Réglages › Premium. StoreKit et votre compte Apple gèrent l’essai, l’achat, le renouvellement, l’annulation et la restauration.' },
        en: { title: 'Premium Pass', subtitle: 'Prices, market, logbook and widget with no ads.', eyebrow: 'CarbuFrance Premium', heading: 'Everything that helps you decide where to refuel.', lead: 'The free version keeps the essentials. Premium removes ads and adds analysis, vehicle tracking and quick actions.', note: '7-day free trial, then the price shown in the app', features: [['No ads', 'No banners, interstitials or rewarded videos.'], ['Market observatory', 'Brent, EUR/USD, trends and news.'], ['Logbook', 'Fill-ups, liters, spending, L/100 km and budget.'], ['Vehicle maintenance', 'Service events, reminders and total cost.'], ['Widget actions', 'Directions, add fill-up and refresh.']], rows: [['Prices, map, list, favorites', true, true], ['Cheapest-station widget', true, true], ['Ads removed', false, true], ['Markets and averages', false, true], ['Logbook, maintenance, widget actions', false, true]], activate: 'Open CarbuFrance › Settings › Premium. StoreKit and your Apple account handle trial, purchase, renewal, cancellation and restoration.' },
        es: { title: 'Pass Premium', subtitle: 'Precios, mercado, registro y widget sin publicidad.', eyebrow: 'CarbuFrance Premium', heading: 'Todo lo que ayuda a decidir dónde repostar.', lead: 'La versión gratuita mantiene lo esencial. Premium elimina anuncios y añade análisis, seguimiento del vehículo y acciones rápidas.', note: '7 días de prueba gratis, luego el precio mostrado en la app', features: [['Sin publicidad', 'Sin banners, intersticiales ni vídeos recompensados.'], ['Observatorio de mercados', 'Brent, EUR/USD, tendencias y noticias.'], ['Registro', 'Repostajes, litros, gastos, L/100 km y presupuesto.'], ['Mantenimiento', 'Intervenciones, recordatorios y coste total.'], ['Acciones widget', 'Ruta, añadir repostaje y actualizar.']], rows: [['Precios, mapa, lista, favoritos', true, true], ['Widget de estación más barata', true, true], ['Anuncios eliminados', false, true], ['Mercados y medias', false, true], ['Registro, mantenimiento, acciones widget', false, true]], activate: 'Abre CarbuFrance › Ajustes › Premium. StoreKit y tu cuenta Apple gestionan prueba, compra, renovación, cancelación y restauración.' },
        it: { title: 'Pass Premium', subtitle: 'Prezzi, mercato, registro e widget senza pubblicità.', eyebrow: 'CarbuFrance Premium', heading: 'Tutto ciò che aiuta a decidere dove fare rifornimento.', lead: 'La versione gratuita mantiene l’essenziale. Premium elimina annunci e aggiunge analisi, gestione veicolo e azioni rapide.', note: '7 giorni di prova gratuita, poi il prezzo mostrato nell’app', features: [['Senza pubblicità', 'Nessun banner, interstitial o video premiato.'], ['Osservatorio mercati', 'Brent, EUR/USD, tendenze e notizie.'], ['Registro', 'Rifornimenti, litri, spese, L/100 km e budget.'], ['Manutenzione', 'Interventi, promemoria e costo totale.'], ['Azioni widget', 'Navigazione, aggiungi rifornimento e aggiorna.']], rows: [['Prezzi, mappa, lista, preferiti', true, true], ['Widget stazione più economica', true, true], ['Annunci rimossi', false, true], ['Mercati e medie', false, true], ['Registro, manutenzione, azioni widget', false, true]], activate: 'Apri CarbuFrance › Impostazioni › Premium. StoreKit e il tuo account Apple gestiscono prova, acquisto, rinnovo, annullamento e ripristino.' },
        de: { title: 'Premium-Pass', subtitle: 'Preise, Markt, Fahrtenbuch und Widget ohne Werbung.', eyebrow: 'CarbuFrance Premium', heading: 'Alles, was bei der Tankentscheidung hilft.', lead: 'Die kostenlose Version enthält das Wesentliche. Premium entfernt Werbung und ergänzt Analyse, Fahrzeugverwaltung und Schnellaktionen.', note: '7 Tage kostenlos testen, danach der in der App angezeigte Preis', features: [['Keine Werbung', 'Keine Banner, Interstitials oder belohnten Videos.'], ['Marktüberblick', 'Brent, EUR/USD, Trends und Nachrichten.'], ['Fahrtenbuch', 'Tankvorgänge, Liter, Ausgaben, L/100 km und Budget.'], ['Fahrzeugwartung', 'Wartungen, Erinnerungen und Gesamtkosten.'], ['Widget-Aktionen', 'Route, Tankvorgang hinzufügen und aktualisieren.']], rows: [['Preise, Karte, Liste, Favoriten', true, true], ['Widget für günstigste Tankstelle', true, true], ['Werbung entfernt', false, true], ['Märkte und Durchschnitte', false, true], ['Fahrtenbuch, Wartung, Widget-Aktionen', false, true]], activate: 'Öffne CarbuFrance › Einstellungen › Premium. StoreKit und dein Apple-Konto übernehmen Testphase, Kauf, Verlängerung, Kündigung und Wiederherstellung.' }
        },
        irvefrance: {
        fr: { title: 'Pass Premium', subtitle: 'Recharge, tarifs réseaux et mobilité électrique sans publicité.', eyebrow: 'IRVEFrance Premium', heading: 'Des décisions de recharge plus claires avant d’arriver à la borne.', lead: 'La version gratuite garde la carte, les bornes, les filtres, les favoris, le mode hors-ligne et le calculateur. Premium retire la publicité et ajoute les tarifs réseaux, les analyses de prix et les conseils de recharge.', note: '7 jours d’essai gratuit, puis 0,99 €/mois dans l’app', features: [['Sans publicité', 'Suppression des bannières, interstitiels et vidéos récompensées.'], ['Tarifs réseaux', 'Ionity, Lidl Charge, Tesla et autres réseaux suivis dans une grille claire.'], ['Analyse du coût', 'Décomposition du prix de recharge, énergie et évolution du marché électrique.'], ['Conseils de recharge', 'Repères pour optimiser durée, puissance, coût et batterie.'], ['Actualités mobilité', 'Informations utiles sur les réseaux et la mobilité électrique.']], rows: [['Carte, liste, détail borne et guidage', true, true], ['Filtres connecteurs, puissance et rayon', true, true], ['Favoris, hors-ligne, Siri et calculateur', true, true], ['Publicités supprimées', false, true], ['Tarifs réseaux de recharge', false, true], ['Analyse de coût et conseils', false, true]], activate: 'Ouvrez IRVEFrance › Réglages › Premium. StoreKit et votre compte Apple gèrent l’essai, l’achat, le renouvellement, l’annulation et la restauration.' },
        en: { title: 'Premium Pass', subtitle: 'Charging, network rates and electric mobility with no ads.', eyebrow: 'IRVEFrance Premium', heading: 'Clearer charging decisions before you reach the station.', lead: 'The free version keeps the map, chargers, filters, favorites, offline mode and calculator. Premium removes ads and adds network rates, price analysis and charging advice.', note: '7-day free trial, then €0.99/month in the app', features: [['No ads', 'No banners, interstitials or rewarded videos.'], ['Network rates', 'Ionity, Lidl Charge, Tesla and other networks in a clear table.'], ['Cost analysis', 'Charging price breakdown, energy and electricity-market changes.'], ['Charging advice', 'Guidance to optimize duration, power, cost and battery.'], ['EV news', 'Useful updates about charging networks and electric mobility.']], rows: [['Map, list, charger detail and directions', true, true], ['Connector, power and radius filters', true, true], ['Favorites, offline, Siri and calculator', true, true], ['Ads removed', false, true], ['Charging network rates', false, true], ['Cost analysis and advice', false, true]], activate: 'Open IRVEFrance › Settings › Premium. StoreKit and your Apple account handle trial, purchase, renewal, cancellation and restoration.' },
        es: { title: 'Pass Premium', subtitle: 'Recarga, tarifas de redes y movilidad eléctrica sin anuncios.', eyebrow: 'IRVEFrance Premium', heading: 'Decisiones de recarga más claras antes de llegar al punto.', lead: 'La versión gratuita conserva mapa, cargadores, filtros, favoritos, modo sin conexión y calculadora. Premium elimina anuncios y añade tarifas de redes, análisis de precios y consejos de recarga.', note: '7 días de prueba gratis, luego 0,99 €/mes en la app', features: [['Sin publicidad', 'Sin banners, intersticiales ni vídeos recompensados.'], ['Tarifas de redes', 'Ionity, Lidl Charge, Tesla y otras redes en una tabla clara.'], ['Análisis del coste', 'Desglose del precio de recarga, energía y evolución eléctrica.'], ['Consejos de recarga', 'Ayuda para optimizar duración, potencia, coste y batería.'], ['Noticias de movilidad', 'Información útil sobre redes y movilidad eléctrica.']], rows: [['Mapa, lista, detalle y ruta', true, true], ['Filtros por conector, potencia y radio', true, true], ['Favoritos, offline, Siri y calculadora', true, true], ['Anuncios eliminados', false, true], ['Tarifas de redes de recarga', false, true], ['Análisis de coste y consejos', false, true]], activate: 'Abre IRVEFrance › Ajustes › Premium. StoreKit y tu cuenta Apple gestionan prueba, compra, renovación, cancelación y restauración.' },
        it: { title: 'Pass Premium', subtitle: 'Ricarica, tariffe reti e mobilità elettrica senza pubblicità.', eyebrow: 'IRVEFrance Premium', heading: 'Decisioni di ricarica più chiare prima di arrivare alla colonnina.', lead: 'La versione gratuita mantiene mappa, colonnine, filtri, preferiti, offline e calcolatore. Premium elimina annunci e aggiunge tariffe reti, analisi prezzi e consigli di ricarica.', note: '7 giorni di prova gratuita, poi 0,99 €/mese nell’app', features: [['Senza pubblicità', 'Nessun banner, interstitial o video premiato.'], ['Tariffe reti', 'Ionity, Lidl Charge, Tesla e altre reti in una griglia chiara.'], ['Analisi costi', 'Scomposizione del prezzo, energia ed evoluzione del mercato elettrico.'], ['Consigli di ricarica', 'Indicazioni per ottimizzare durata, potenza, costo e batteria.'], ['Notizie mobilità', 'Aggiornamenti utili su reti e mobilità elettrica.']], rows: [['Mappa, lista, dettaglio e navigazione', true, true], ['Filtri connettori, potenza e raggio', true, true], ['Preferiti, offline, Siri e calcolatore', true, true], ['Annunci rimossi', false, true], ['Tariffe reti di ricarica', false, true], ['Analisi costi e consigli', false, true]], activate: 'Apri IRVEFrance › Impostazioni › Premium. StoreKit e il tuo account Apple gestiscono prova, acquisto, rinnovo, annullamento e ripristino.' },
        de: { title: 'Premium-Pass', subtitle: 'Laden, Netzwerktarife und Elektromobilität ohne Werbung.', eyebrow: 'IRVEFrance Premium', heading: 'Klarere Ladeentscheidungen, bevor du die Säule erreichst.', lead: 'Die kostenlose Version enthält Karte, Ladepunkte, Filter, Favoriten, Offline-Modus und Rechner. Premium entfernt Werbung und ergänzt Netzwerktarife, Preisanalysen und Ladehinweise.', note: '7 Tage kostenlos testen, danach 0,99 €/Monat in der App', features: [['Keine Werbung', 'Keine Banner, Interstitials oder belohnten Videos.'], ['Netzwerktarife', 'Ionity, Lidl Charge, Tesla und weitere Netze in einer klaren Tabelle.'], ['Kostenanalyse', 'Preisaufschlüsselung, Energie und Entwicklung des Strommarkts.'], ['Ladehinweise', 'Tipps zur Optimierung von Dauer, Leistung, Kosten und Batterie.'], ['E-Mobility-News', 'Nützliche Infos zu Ladenetzen und Elektromobilität.']], rows: [['Karte, Liste, Details und Route', true, true], ['Filter für Anschluss, Leistung und Radius', true, true], ['Favoriten, offline, Siri und Rechner', true, true], ['Werbung entfernt', false, true], ['Ladenetz-Tarife', false, true], ['Kostenanalyse und Hinweise', false, true]], activate: 'Öffne IRVEFrance › Einstellungen › Premium. StoreKit und dein Apple-Konto übernehmen Testphase, Kauf, Verlängerung, Kündigung und Wiederherstellung.' }
        }
    };

    function langFromPage() {
        var queryLang = new URLSearchParams(window.location.search).get('lang');
        var savedLang = window.localStorage.getItem('rv-apps-language');
        var browserLang = (navigator.language || 'fr').slice(0, 2).toLowerCase();
        var lang = queryLang || savedLang || browserLang;
        return supported.indexOf(lang) === -1 ? 'fr' : lang;
    }

    function withLang(path, lang) {
        if (!path || path.indexOf('http') === 0 || path.indexOf('mailto:') === 0) return path;
        return path + (path.indexOf('?') === -1 ? '?' : '&') + 'lang=' + lang;
    }

    function escapeHTML(value) {
        return String(value).replace(/[&<>"]/g, function (character) {
            return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[character];
        });
    }

    function paragraph(text) { return '<p>' + text + '</p>'; }
    function icon(app) { return './icons/' + app.icon; }
    function languageSwitcher(lang) {
        return '<nav class="language-switcher" aria-label="Langue">' + supported.map(function (code) {
            return '<button class="language-button' + (code === lang ? ' is-active' : '') + '" type="button" data-lang="' + code + '" aria-pressed="' + (code === lang ? 'true' : 'false') + '">' + code.toUpperCase() + '</button>';
        }).join('') + '</nav>';
    }

    function header(lang, app, title, subtitle) {
        return '<header class="page-header site-page-header"><div class="page-header-inner"><a href="' + withLang('./index.html', lang) + '" class="page-icon-link" aria-label="' + ui[lang].home + '"><img src="' + icon(app) + '" alt="' + app.name + '" class="page-icon"></a><div><p class="premium-eyebrow">' + escapeHTML(app.name) + '</p><h1 class="page-title">' + escapeHTML(title) + '</h1></div></div><p class="page-subtitle">' + escapeHTML(subtitle) + '</p>' + languageSwitcher(lang) + '</header>';
    }

    function footer(lang, appName) {
        return '<footer class="page-footer"><p>&copy; 2026 ' + escapeHTML(appName) + ' — Rodolphe Vandaele</p></footer>';
    }

    function renderSections(sections) {
        return sections.map(function (section) {
            var body = section.html ? section.html : section.items ? '<ul class="summary-list">' + section.items.map(function (item) { return '<li><p>' + item + '</p></li>'; }).join('') + '</ul>' : section.paragraphs.map(paragraph).join('');
            return '<div class="page-section"><h2>' + escapeHTML(section.title) + '</h2>' + body + '</div>';
        }).join('');
    }

    function renderFAQ(items) {
        return items.map(function (item) { return '<div class="faq-item"><p class="faq-q">' + escapeHTML(item[0]) + '</p><p class="faq-a">' + escapeHTML(item[1]) + '</p></div>'; }).join('');
    }

    function renderSupport(lang, app) {
        var labels = ui[lang];
        var text = typeText[app.type][lang];
        var appKey = Object.keys(apps).filter(function (key) { return apps[key] === app; })[0];
        var features = appFeatures[appKey] ? appFeatures[appKey][lang] : [app.description[lang]];
        var sections = [
            { title: labels.quickSupport, items: [app.description[lang], text.source, app.name + ' iOS 18+', labels.email + ' : ' + mail] },
            { title: commonCopy[lang].featuresTitle, items: features },
            { title: labels.faqTitle, html: renderFAQ(text.support) },
            { title: labels.contactTitle, html: '<p><a href="mailto:' + mail + '?subject=Support%20' + encodeURIComponent(app.name) + '" class="store-link">' + labels.email + '</a></p>' },
            { title: labels.deleteTitle, paragraphs: [commonCopy[lang].deletion] }
        ];
        return header(lang, app, labels.support, app.description[lang]) + '<main class="premium-page"><section class="page-card premium-hero-clean"><p class="premium-eyebrow">' + labels.support + '</p><h2 class="premium-heading">' + escapeHTML(app.name) + '</h2><p class="premium-lead">' + escapeHTML(app.description[lang]) + '</p></section><section class="page-card">' + renderSections(sections) + '</section></main>' + footer(lang, app.name);
    }

    function adText(lang, app) {
        var storeKit = {
            fr: 'Les achats intégrés sont gérés par StoreKit et votre compte Apple. Aucune donnée bancaire n’est reçue par l’application.',
            en: 'In-app purchases are handled by StoreKit and your Apple account. The app never receives payment card data.',
            es: 'Las compras integradas las gestionan StoreKit y tu cuenta Apple. La app no recibe datos bancarios.',
            it: 'Gli acquisti in-app sono gestiti da StoreKit e dal tuo account Apple. L’app non riceve dati bancari.',
            de: 'In-App-Käufe werden von StoreKit und deinem Apple-Konto verwaltet. Die App erhält keine Zahlungsdaten.'
        };
        var ads = {
            fr: 'La version gratuite peut afficher des publicités via Google AdMob selon votre consentement App Tracking Transparency.',
            en: 'The free version may display ads through Google AdMob depending on your App Tracking Transparency consent.',
            es: 'La versión gratuita puede mostrar anuncios mediante Google AdMob según tu consentimiento de App Tracking Transparency.',
            it: 'La versione gratuita può mostrare annunci tramite Google AdMob secondo il consenso App Tracking Transparency.',
            de: 'Die kostenlose Version kann je nach App-Tracking-Transparency-Einwilligung Werbung über Google AdMob anzeigen.'
        };
        if (app.type === 'toilet' || app.type === 'defib') return ads[lang] + ' ' + (lang === 'fr' ? 'Aucun achat Premium n’est utilisé.' : lang === 'en' ? 'No Premium purchase is used.' : lang === 'es' ? 'No se usa compra Premium.' : lang === 'it' ? 'Non viene usato alcun acquisto Premium.' : 'Es wird kein Premium-Kauf verwendet.');
        if (app.type === 'sos') return ads[lang] + ' ' + storeKit[lang];
        return ads[lang] + ' ' + storeKit[lang];
    }

    function renderPrivacy(lang, app) {
        var labels = ui[lang];
        var text = typeText[app.type][lang];
        var sections = [
            { title: '1. ' + labels.dataUsed, paragraphs: [text.data] },
            { title: '2. ' + labels.business, paragraphs: [adText(lang, app), commonCopy[lang].adDetails] },
            { title: '3. ' + labels.sources, paragraphs: [text.source] },
            { title: '4. ' + labels.retention, paragraphs: [commonCopy[lang].retention] },
            { title: '5. ' + labels.rightsTitle, paragraphs: [labels.rights] },
            { title: '6. ' + labels.contactTitle, paragraphs: ['<a href="mailto:' + mail + '">' + mail + '</a>'] }
        ];
        return header(lang, app, labels.privacy, app.name + ' — ' + labels.updated) + '<main class="premium-page"><section class="page-card premium-hero-clean"><p class="premium-eyebrow">' + labels.privacy + '</p><h2 class="premium-heading">' + escapeHTML(app.name) + '</h2><p class="premium-lead">' + escapeHTML(text.data) + '</p></section><section class="page-card">' + renderSections(sections) + '</section></main>' + footer(lang, app.name);
    }

    function renderPremium(lang) {
        var appKey = document.body.getAttribute('data-app') || 'carbufrance';
        var app = apps[appKey] || apps.carbufrance;
        var dataSet = premium[appKey] || premium.carbufrance;
        var data = dataSet[lang];
        var labels = ui[lang];
        var features = data.features.map(function (feature) { return '<article class="premium-feature-card"><h3>' + escapeHTML(feature[0]) + '</h3><p>' + escapeHTML(feature[1]) + '</p></article>'; }).join('');
        var rows = data.rows.map(function (row) { return '<div class="premium-comparison-row"><span>' + escapeHTML(row[0]) + '</span><span class="premium-state ' + (row[1] ? 'is-included' : '') + '">' + (row[1] ? labels.yes : labels.no) + '</span><span class="premium-state ' + (row[2] ? 'is-premium' : '') + '">' + (row[2] ? labels.yes : labels.no) + '</span></div>'; }).join('');
        return header(lang, app, data.title, data.subtitle) + '<main class="premium-page"><section class="page-card premium-hero-clean"><p class="premium-eyebrow">' + escapeHTML(data.eyebrow) + '</p><h2 class="premium-heading">' + escapeHTML(data.heading) + '</h2><p class="premium-lead">' + escapeHTML(data.lead) + '</p><span class="premium-note">' + escapeHTML(data.note) + '</span></section><section class="page-card"><h2 class="premium-section-title">' + labels.included + '</h2><div class="premium-feature-grid">' + features + '</div></section><section class="page-card"><h2 class="premium-section-title">' + labels.free + ' / Premium</h2><div class="premium-comparison"><div class="premium-comparison-row premium-comparison-head"><span>' + commonCopy[lang].feature + '</span><span>' + labels.free + '</span><span>Premium</span></div>' + rows + '</div></section><section class="page-card"><div class="page-section"><h2>StoreKit</h2><p>' + escapeHTML(data.activate) + '</p><div class="cta-block"><a href="' + app.store + '" class="btn-premium">' + labels.download + ' ' + app.name + '</a><p>iPhone · iPad · iOS 18+</p></div></div></section></main>' + footer(lang, app.name);
    }

    function renderHome(lang) {
        var labels = ui[lang];
        function card(key) {
            var app = apps[key];
            var links = '<a href="' + withLang('./' + key + '-support.html', lang) + '" class="link-url">' + labels.support + '</a><a href="' + withLang('./' + key + '-privacy.html', lang) + '" class="link-url">' + labels.privacy + '</a>' + (app.premiumPage ? '<a href="' + withLang('./' + key + '-premium.html', lang) + '" class="link-url">' + labels.premium + '</a>' : '');
            var action = app.store ? '<a href="' + app.store + '" class="store-link-badge">' + labels.appStore + '</a>' : '<span class="store-link-badge store-link-disabled">' + labels.soon + '</span>';
            return '<article class="page-card site-app-card"><div class="card-header"><img src="' + icon(app) + '" alt="' + app.name + '" class="app-icon"><div><h2 class="app-title">' + app.name + '</h2><span class="app-badge ' + (app.status === 'soon' ? 'app-badge-muted' : '') + '">' + (app.status === 'soon' ? labels.soon : labels.available) + '</span></div></div><p class="card-content">' + escapeHTML(app.description[lang]) + '</p><div class="site-link-stack">' + links + '</div>' + action + '</article>';
        }
        var availableCards = Object.keys(apps).filter(function (key) { return apps[key].status !== 'soon'; }).map(card).join('');
        var soonCards = Object.keys(apps).filter(function (key) { return apps[key].status === 'soon'; }).map(card).join('');
        var soonSection = soonCards ? '<section><h2 class="premium-section-title">' + labels.soon + '</h2><div class="site-app-grid site-app-grid-soon">' + soonCards + '</div></section>' : '';
        return '<header class="page-card premium-hero-clean site-home-hero"><p class="premium-eyebrow">' + labels.developer + '</p><h1 class="premium-heading">Rodolphe Vandaele</h1><p class="premium-lead">' + commonCopy[lang].homeLead + '</p>' + languageSwitcher(lang) + '</header><main class="premium-page"><section><h2 class="premium-section-title">' + labels.available + '</h2><div class="site-app-grid">' + availableCards + '</div></section>' + soonSection + '<section class="page-card site-profile-card"><img src="./images/Profile.jpeg" alt="Rodolphe Vandaele" class="site-profile-photo"><div><p class="premium-eyebrow">' + labels.profile + '</p><h2 class="premium-section-title">Rodolphe Vandaele</h2><p>' + labels.developer + '</p><a href="' + withLang('./about.html', lang) + '" class="store-link">' + labels.about + '</a></div></section></main><footer class="site-footer"><p>&copy; 2026 Rodolphe Vandaele · <a href="mailto:' + mail + '">' + mail + '</a></p></footer>';
    }

    function renderAbout(lang) {
        var labels = ui[lang];
        var bios = {
            fr: ['Développeur iOS autodidacte, je construis des apps simples, utiles et respectueuses de la vie privée.', 'Je privilégie SwiftUI, StoreKit, MapKit, Core Location, WidgetKit et les composants natifs Apple pour garder une expérience cohérente.'],
            en: ['Self-taught iOS developer building simple, useful and privacy-minded apps.', 'I favor SwiftUI, StoreKit, MapKit, Core Location, WidgetKit and native Apple components for a coherent experience.'],
            es: ['Desarrollador iOS autodidacta que crea apps simples, útiles y respetuosas con la privacidad.', 'Uso SwiftUI, StoreKit, MapKit, Core Location, WidgetKit y componentes nativos de Apple para una experiencia coherente.'],
            it: ['Sviluppatore iOS autodidatta che crea app semplici, utili e rispettose della privacy.', 'Uso SwiftUI, StoreKit, MapKit, Core Location, WidgetKit e componenti nativi Apple per un’esperienza coerente.'],
            de: ['Autodidaktischer iOS-Entwickler für einfache, nützliche und datenschutzfreundliche Apps.', 'Ich nutze SwiftUI, StoreKit, MapKit, Core Location, WidgetKit und native Apple-Komponenten für ein stimmiges Erlebnis.']
        };
        return '<header class="page-card premium-hero-clean site-about-hero"><img src="./images/Profile.jpeg" alt="Rodolphe Vandaele" class="site-about-photo"><p class="premium-eyebrow">' + labels.developer + '</p><h1 class="premium-heading">Rodolphe Vandaele</h1><p class="premium-lead">' + escapeHTML(bios[lang][0]) + '</p>' + languageSwitcher(lang) + '</header><main class="premium-page"><section class="page-card"><div class="page-section"><h2>' + labels.about + '</h2>' + bios[lang].map(function (item) { return '<p>' + escapeHTML(item) + '</p>'; }).join('') + '</div><div class="page-section"><h2>' + labels.apps + '</h2><div class="premium-feature-grid">' + Object.keys(apps).map(function (key) { var app = apps[key]; return '<article class="premium-feature-card"><h3>' + app.name + '</h3><p>' + escapeHTML(app.description[lang]) + '</p></article>'; }).join('') + '</div></div><div class="page-section"><h2>' + labels.contactTitle + '</h2><p><a href="mailto:' + mail + '" class="store-link">' + labels.email + '</a></p></div></section></main>' + footer(lang, 'Rodolphe Vandaele');
    }

    function render() {
        var root = document.getElementById('site-root');
        if (!root) return;
        var lang = langFromPage();
        var page = document.body.getAttribute('data-page') || 'home';
        var appKey = document.body.getAttribute('data-app');
        var app = apps[appKey];
        document.documentElement.lang = lang;
        window.localStorage.setItem('rv-apps-language', lang);
        if (page === 'home') root.innerHTML = renderHome(lang);
        if (page === 'about') root.innerHTML = renderAbout(lang);
        if (page === 'premium') root.innerHTML = renderPremium(lang);
        if (page === 'support' && app) root.innerHTML = renderSupport(lang, app);
        if (page === 'privacy' && app) root.innerHTML = renderPrivacy(lang, app);
        document.querySelectorAll('[data-lang]').forEach(function (button) {
            button.addEventListener('click', function () {
                var nextLang = button.getAttribute('data-lang');
                var url = new URL(window.location.href);
                url.searchParams.set('lang', nextLang);
                window.location.href = url.toString();
            });
        });
    }

    render();
})();